name: Data Scraping and Upload

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering of the workflow as well

jobs:
  upload-to-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Force Node.js version 16

      - name: Checkout the repository
        uses: actions/checkout@v3  # Make sure to use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Explicitly set to the latest version
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to avoid old version issues
          pip install -r requirements.txt

      - name: Clear GitHub Actions cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create credentials file
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          ec
