name: Data Scraping and Upload

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering of the workflow as well

jobs:
  upload-to-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Clear existing actions cache
        run: |
          sudo rm -rf ${{ runner.tool_cache }}/*  # Force clearing of tool cache

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json

      - name: Run Python script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/credentials.json
        run: python main.py
